.TH material 3

.SH NAME
material

.SH SYNOPSIS
Routines for evaluating rational and polynomial Bezier curves and
their derivatives.

.SH SYNTAX

.B #include "bezier.h"

.SH DESCRIPTION:

A library for dealing with materials.  A number of materials are
pre-defined and can be referred to by name.  The following are
the C structures that are used.

.nf
typedef struct {
    double r, g, b;
} Color;

typedef struct {
    Color diffuse;
    Color specular;
    int specularity;
    char* name;		/* used internally; 
			   should only be read by user */
} Material;
.fi

The following are the names of the pre-defined materials:

.nf
  NullMaterial, 
  RedPlastic,
  NewBlue,
  NewGreen,
  NewPurple,
  RedMatte,
  GreenPlastic,
  DarkGreenPlastic,
  GreenMatte,
  BluePlastic,
  BlueMatte,
  YellowPlastic,
  YellowMatte,
  PurplePlastic,
  PurpleMatte,
  Steel,
  White,
  Black
.fi

.nf
.B Material MaterialCreate(dr, dg, db, sr, sg, sb, spec)
.B double dr,dg,db,sr,sg,sb;
.B int spec;
.fi


Create and return a new material.
The diffuse reflection in the red, green, and blue channels
is given by dr, dg, and db; the specular reflection is given
by sr, sg, and sb; the Phong coefficient is given by spec.


.nf
.B  void MaterialWrite( fp, m)
.B  FILE *fp;
.B  Material m;
.fi

Write a material on the given stream.

.nf
.B  int MaterialRead( fp, mp)
.B  FILE *fp;
.B  Material *mp;
.fi

Read in a material descriptor from the given stream.  One is returned
on success, zero on end of file.

.nf
.B  int MaterialLookup( name, mp)
.B  char *name;
.B  Material *mp;
.fi

Set the material pointed to by mp to the named material.  Returned is
one on success, zero otherwise.

.nf
.B  int IsNullMaterial( m)
.B  Material m;
.fi

Return one if the given material is equivalent to the null material.
Return zero otherwise.

.nf
.B  Material KMat(k, kmin, kmax, gamma)
.B  double k, kmin, kmax, gamma;
.fi

Return a material based on the value k.  k will be clamped to be in
the range kmin to kmax.  If kmax < kmin, the null material is returned.
The color assigned is an HLS color, where H is k (mapped to -1,1),
L is .5, and S is .9.  The hue range is 240.  A suggested gamma value
is 0.625.


.SH DATE
January 3, 1992
